import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/Header";
import Nav from "@/components/shared/Nav";
import Sidebar from "@/components/shared/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Bespoke Custom Uniques",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className=" bg-modernDolchLight-caret-color bg-fixed scroll-smooth ">
                    <main id="mainmain" className="max-w-[100vw] my-0 mx-auto min-h-screen p-1 ">
                        <section className="fixed left-1 right-1 top-0 z-50 mx-auto my-0 w-1/2">
                            <Header />
                        </section>

                        <div className="mt-4">{children}</div>
                    </main>
                </div>
            </body>
        </html>
    );
}
